@extends('master')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <h4 class="page-title float-left text-capitalize">{{ $page_title }}</h4>

                        <ol class="breadcrumb float-right text-capitalize">
                            <li class="breadcrumb-item"><a href="#">Admin</a></li>
                            <li class="breadcrumb-item"><a href="#">{{ $page_title }}</a></li>
                            <li class="breadcrumb-item active">{{ $page_title }} list</li>
                        </ol>

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- end row -->
            
            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <div style="display:flex; justify-content:space-between;margin:0 14px; ">
                            <h4 class="header-title m-b-15 m-t-0">{{ $page_title }} List</h4>

                        </div>

                        <table
                            class="table table-hover table-bordered m-0 tickets-list table-actions-bar dt-responsive nowrap"
                            cellspacing="0" width="100%" id="datatable">
                            <thead>
                                <tr class="text-capitalize">
                                    <th>SL</th>
                                    <th>Year</th>
                                    <th>Month</th>
                                    <th>Grand Total</th>
                                    <th>Generated By</th>
                                    <th class="hidden-sm">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @if (!empty($payrolls))
                                    @foreach ($payrolls as $key => $payroll)
                                        @php
                                            if ($payroll->month == 1) {
                                                $payroll_month = 'January';
                                            } elseif ($payroll->month == 2) {
                                                $payroll_month = 'February';
                                            } elseif ($payroll->month == 3) {
                                                $payroll_month = 'March';
                                            } elseif ($payroll->month == 4) {
                                                $payroll_month = 'April';
                                            } elseif ($payroll->month == 5) {
                                                $payroll_month = 'May';
                                            } elseif ($payroll->month == 6) {
                                                $payroll_month = 'June';
                                            } elseif ($payroll->month == 7) {
                                                $payroll_month = 'July';
                                            } elseif ($payroll->month == 8) {
                                                $payroll_month = 'August';
                                            } elseif ($payroll->month == 9) {
                                                $payroll_month = 'September';
                                            } elseif ($payroll->month == 10) {
                                                $payroll_month = 'October';
                                            } elseif ($payroll->month == 11) {
                                                $payroll_month = 'November';
                                            } elseif ($payroll->month == 12) {
                                                $payroll_month = 'December';
                                            } else {
                                                $payroll_month = 'Not Found';
                                            }
                                        @endphp

                                        <tr>
                                            <td scope="row">{{ ++$key }}</td>
                                            <td>{{ $payroll->year ?? '' }}</td>
                                            <td>{{ $payroll_month }}</td>
                                            <td>{{ $payroll->grand_total ?? '' }}</td>
                                            <td>{{ $payroll->data_inputed_by->name ?? '' }}</td>
                                            <td>
                                                <div class="btn-group dropdown">
                                                    <a href="javascript: void(0);" class="table-action-btn dropdown-toggle"
                                                        data-toggle="dropdown" aria-expanded="false"><i
                                                            class="mdi mdi-dots-horizontal"></i></a>
                                                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                                                        <a class="dropdown-item "
                                                            href="{{ route('payroll.show', $payroll->id) }}"
                                                            type="submit"><i
                                                                class="mdi mdi-eye m-r-10 font-18 text-muted vertical-middle"></i>
                                                            View
                                                        </a>

                                                        <a class="dropdown-item "
                                                            href="{{ route('payroll.edit', $payroll->id) }}"
                                                            type="submit"><i
                                                                class="mdi mdi-pencil m-r-10 text-muted font-18 vertical-middle"></i>
                                                            Edit
                                                        </a>
                                                        <a class="dropdown-item"
                                                            href="{{ route('payroll.delete', $payroll->id) }}"
                                                            onclick="return confirm('Are you sure to delete it ?')">
                                                            <i
                                                                class="mdi mdi-delete m-r-10 text-muted font-18 vertical-middle"></i>
                                                            Delete
                                                        </a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
